### ISSUE TITLE
vsearch cluster-features-de-novo fatal error

### ISSUE THREAD

**Issue by stan-iakhno** [qiime2/q2-vsearch#65]
Hi there, and thanks for your tremendous effort in maintaining q2!

I am running _vsearch cluster-features-de-novo_ with the hope to re-cluster my AVS table inferred from DADA2. The following command:
`  qiime vsearch cluster-features-de-novo --i-sequences rep-seqs.qza --i-table feature-table.qza --p-perc-identity .99 --p-threads 6 --output-dir OUT --verbose`
spits out this traceback: 
```
Running external command line application. This may print messages to stdout and/or stderr.
The command being run is below. This command cannot be manually re-run as it will depend on temporary files that no longer exist.

Command: vsearch --cluster_size /tmp/tmpgm9lrl9r --id 0.99 --centroids /tmp/q2-DNAFASTAFormat-zdyznqtj --uc /tmp/tmpz0fek351 --qmask none --xsize --threads 6

vsearch v2.7.0_linux_x86_64, 31.1GB RAM, 8 cores
https://github.com/torognes/vsearch

Reading file /tmp/tmpgm9lrl9r 4%  

Fatal error: Invalid (zero) abundance annotation in FASTA file header
Traceback (most recent call last):
  File "/root/miniconda2/envs/qiime2-2019.7/lib/python3.6/site-packages/q2cli/commands.py", line 327, in __call__
    results = action(**arguments)
  File "</root/miniconda2/envs/qiime2-2019.7/lib/python3.6/site-packages/decorator.py:decorator-gen-121>", line 2, in cluster_features_de_novo
  File "/root/miniconda2/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 240, in bound_callable
    output_types, provenance)
  File "/root/miniconda2/envs/qiime2-2019.7/lib/python3.6/site-packages/qiime2/sdk/action.py", line 383, in _callable_executor_
    output_views = self._callable(**view_args)
  File "/root/miniconda2/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_vsearch/_cluster_features.py", line 193, in cluster_features_de_novo
    run_command(cmd)
  File "/root/miniconda2/envs/qiime2-2019.7/lib/python3.6/site-packages/q2_vsearch/_cluster_features.py", line 33, in run_command
    subprocess.run(cmd, check=True)
  File "/root/miniconda2/envs/qiime2-2019.7/lib/python3.6/subprocess.py", line 418, in run
    output=stdout, stderr=stderr)
subprocess.CalledProcessError: Command '['vsearch', '--cluster_size', '/tmp/tmpgm9lrl9r', '--id', '0.99', '--centroids', '/tmp/q2-DNAFASTAFormat-zdyznqtj', '--uc', '/tmp/tmpz0fek351', '--qmask', 'none', '--xsize', '--threads', '6']' returned non-zero exit status 1.

Plugin error from vsearch:

  Command '['vsearch', '--cluster_size', '/tmp/tmpgm9lrl9r', '--id', '0.99', '--centroids', '/tmp/q2-DNAFASTAFormat-zdyznqtj', '--uc', '/tmp/tmpz0fek351', '--qmask', 'none', '--xsize', '--threads', '6']' returned non-zero exit status 1.
```
Could you kindly suggest a solution to this issue?

With thanks, Stan

**Comment by nbokulich** [comment]
Hi @stan-iakhno please post your question to the [QIIME 2 forum](http://forum.qiime2.org), all technical support is provided there. Thank you!
